import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderMegaMenu } from "@/components/HeaderMegaMenu/HeaderMegaMenu";
import Providers from "@/components/Providers";
import ToastProvider from "@/components/ToastProvider/toast.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Octopus Market",
  description: "Generated by fatihcalis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ToastProvider>
            {/* <HeaderMegaMenu /> */}
            {children}
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
