import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderMegaMenu } from "@/components/HeaderMegaMenu/HeaderMegaMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Octopus Market",
  description: "Generated by fatihcalis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMegaMenu />
        {children}
      </body>
    </html>
  );
}
